/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xya_csu_utility_YykReader */

#ifndef _Included_com_xya_csu_utility_YykReader
#define _Included_com_xya_csu_utility_YykReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xya_csu_utility_YykReader
 * Method:    setDataDir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xya_csu_utility_YykReader_setDataDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xya_csu_utility_YykReader
 * Method:    listDict
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xya_csu_utility_YykReader_listDict
  (JNIEnv *, jobject);

/*
 * Class:     com_xya_csu_utility_YykReader
 * Method:    useDict
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_com_xya_csu_utility_YykReader_useDict
  (JNIEnv *, jobject, jstring,jstring);

/*
 * Class:     com_xya_csu_utility_YykReader
 * Method:    searchKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xya_csu_utility_YykReader_searchKey
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
